"""empty message

Revision ID: d7bc6a4253ff
Revises: f4bb24b03795
Create Date: 2024-12-28 22:09:07.917221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bc6a4253ff'
down_revision = 'f4bb24b03795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=150), nullable=True, server_defalut='temp'))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True, server_defalut='temp'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('file_path')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
